### PR TITLE
Update TelemetryConfiguration.Active on README

### PR DESCRIPTION
**Pull request by rodolphocastro**
TelemetryConfiguration.Active is now obsolete, this commits updates the docs to help new users.

### CODE REVIEW

**Comment by triforcely** [comment]
This doesn' work well when used alongside services.AddApplicationInsightsTelemetry() - traces are not correlated with requests correctly.

**Comment by rodolphocastro** [comment]
@triforcely weren't we supposed to turn off the default `services.UseApplicationInsights()` and instead let this Sink handle it? Got those instructions from Serilog's [readme](https://github.com/serilog/serilog-aspnetcore/blob/dev/README.md)

**Comment by triforcely** [comment]
What about tracking calls to dependencies, performance counters, etc.?

**Comment by rodolphocastro** [comment]
Keeping `services.AddApplicationInsightsTelemetry();` should still give you all the telemetry. I'll double check just to be sure and I'll return to you

**Comment by rodolphocastro** [comment]
@triforcely just checked and tracking remote dependencies and requests are working when using `TelemetryConfiguration.CreateDefault()` alongside `services.AddApplicationInsightsTelemetry()`

image

**Comment by triforcely** [comment]
Yes, but since they are using two different connections, logs are not as nicely correlated - this is specifically shown in "live metrics". When I was using "Active", I'd get error logs in the telemetry view just after the request was made. After using "CreateDefault()" approach, logs are missing from there. I can still browse the data separately (e.g. query "traces" in logs and view exceptions with dependency tracking) but it is not as good as before, so what I'm trying to suggest is that we need to find a way of getting existing TelemetryConfiguration from DI, because I guess that some "magic" happens internally, when different telemetry sources are batched together. I might be able to do a repro of what I've observed between these two approaches in a few days.

**Comment by dnperfors** [comment]
The suggestion in #160 would be better in most situations.

**Comment by nblumhardt** [comment]
I'll close this as #160 is merged, if it's possible to improve that option to make it more discoverable we should work forward from there, I think. Thanks all the same @rodolphocastro ! 👍

**Pull request closed without merging**
